title: Dog Blog
author: kirstenjoy1
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 I have no idea what I'm doing so here's a blog about my dog, Quest.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  kirstenjoy1 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
